/*
 * File: app/view/InitialViewArea.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('syncbook.view.InitialViewArea', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.InitialViewArea_ua',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.Img',
        'Ext.grid.column.Date',
        'Ext.form.field.Date'
    ],

    itemId: 'myviewport',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    itemId: 'groupTabbedPane',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'groupName',
                            title: 'Federico Nildric Longhin',
                            titleAlign: 'center',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    frame: true,
                                    itemId: 'chooseContactGrid',
                                    rtl: false,
                                    autoScroll: true,
                                    bodyBorder: true,
                                    overlapHeader: true,
                                    title: 'Choose Contact',
                                    titleAlign: 'center',
                                    columnLines: true,
                                    emptyText: 'Empty Storage',
                                    enableColumnHide: false,
                                    enableColumnMove: false,
                                    enableColumnResize: false,
                                    enableLocking: true,
                                    forceFit: false,
                                    store: 'ContactDatabaseStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 150,
                                            align: 'center',
                                            dataIndex: 'contactColor',
                                            groupable: true,
                                            menuDisabled: true,
                                            text: 'Color',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 150,
                                            align: 'center',
                                            dataIndex: 'contactSurname',
                                            groupable: true,
                                            text: 'Surname',
                                            flex: 2
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 150,
                                            align: 'center',
                                            dataIndex: 'contactName',
                                            groupable: true,
                                            text: 'Name',
                                            flex: 2
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'bottom',
                                            frame: false,
                                            autoScroll: true,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'addContactButton',
                                                    text: 'Add Contact'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'modContactButton',
                                                    text: 'Mod Contact'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'deleteContactButton',
                                                    text: 'Delete Contact'
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'syncContactButton',
                                                    text: 'Sync Contacts'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'optionsContact',
                                                    glyph: 'xf013@FontAwesome'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'form',
                                    flex: 2,
                                    frame: true,
                                    height: 400,
                                    itemId: 'singleContactForm',
                                    maxHeight: 400,
                                    autoScroll: true,
                                    layout: 'absolute',
                                    title: 'Contact Information',
                                    titleAlign: 'center',
                                    method: 'POST',
                                    waitTitle: 'Loading...',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            x: 20,
                                            y: 40,
                                            cls: 'textFieldCSS',
                                            itemId: 'typeTextField',
                                            fieldLabel: 'Type',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactType',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 210,
                                            y: 40,
                                            cls: 'textFieldCSS',
                                            itemId: 'nameTextField',
                                            fieldLabel: 'Name',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactName',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 400,
                                            y: 40,
                                            cls: 'textFieldCSS',
                                            itemId: 'usernameTextField',
                                            fieldLabel: 'Username',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactUsername',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 590,
                                            y: 40,
                                            cls: 'textFieldCSS',
                                            itemId: 'surnameTextField',
                                            fieldLabel: 'Surname',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactSurname',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 780,
                                            y: 40,
                                            cls: 'textFieldCSS',
                                            itemId: 'eMailTextField',
                                            fieldLabel: 'E-Mail',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactEMail',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 20,
                                            y: 130,
                                            cls: 'textFieldCSS',
                                            itemId: 'phoneNumberTextField',
                                            fieldLabel: 'Phone Number',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactPhoneNumber',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 210,
                                            y: 130,
                                            cls: 'textFieldCSS',
                                            itemId: 'mobileNumberTextField',
                                            fieldLabel: 'Mobile Number',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactMobileNumber',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 400,
                                            y: 130,
                                            cls: 'textFieldCSS',
                                            itemId: 'faxTextField',
                                            fieldLabel: 'Fax',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactFax',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 590,
                                            y: 130,
                                            cls: 'textFieldCSS',
                                            itemId: 'addressTextField',
                                            fieldLabel: 'Address',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactAddress',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 780,
                                            y: 130,
                                            cls: 'textFieldCSS',
                                            itemId: 'webAddressTextField',
                                            fieldLabel: 'Web Address',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactWeb',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 20,
                                            y: 220,
                                            cls: 'textFieldCSS',
                                            itemId: 'partitaIvaTextField',
                                            fieldLabel: 'Partita Iva',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactPartitaIva',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 210,
                                            y: 220,
                                            cls: 'textFieldCSS',
                                            itemId: 'codiceFiscaleTextField',
                                            fieldLabel: 'Codice Fiscale',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactCodiceFiscale',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 20,
                                            y: 310,
                                            cls: 'textFieldCSS',
                                            itemId: 'facebookTextField',
                                            fieldLabel: 'Facebook',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactFacebook',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 210,
                                            y: 310,
                                            cls: 'textFieldCSS',
                                            itemId: 'twitterTextField',
                                            fieldLabel: 'Twitter',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactTwitter',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 400,
                                            y: 310,
                                            cls: 'textFieldCSS',
                                            itemId: 'instagramTextField',
                                            fieldLabel: 'Instagram',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactInstagram',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 590,
                                            y: 310,
                                            cls: 'textFieldCSS',
                                            itemId: 'googleTextField',
                                            fieldLabel: 'Google+',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactGoogle',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 780,
                                            y: 310,
                                            cls: 'textFieldCSS',
                                            itemId: 'linkedinTextField',
                                            fieldLabel: 'Linkedin',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactLinkedin',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 970,
                                            y: 310,
                                            cls: 'textFieldCSS',
                                            itemId: 'skypeTextField',
                                            fieldLabel: 'Skype',
                                            labelAlign: 'top',
                                            labelCls: 'x-form-item-label, styleSincbook',
                                            labelSeparator: ' ',
                                            name: 'contactSkype',
                                            fieldCls: 'x-form-field textFieldCSS',
                                            readOnly: true,
                                            emptyCls: 'x-form-empty-field;',
                                            emptyText: 'Choose a Contact'
                                        },
                                        {
                                            xtype: 'label',
                                            x: 10,
                                            y: 10,
                                            cls: 'textFieldCSS',
                                            height: 10,
                                            text: 'Contact Basic Information'
                                        },
                                        {
                                            xtype: 'label',
                                            x: 10,
                                            y: 100,
                                            cls: 'textFieldCSS',
                                            height: 10,
                                            text: 'Contact Numbers and Addresses'
                                        },
                                        {
                                            xtype: 'label',
                                            x: 10,
                                            y: 190,
                                            cls: 'textFieldCSS',
                                            height: 10,
                                            text: 'Contact Advanced Information'
                                        },
                                        {
                                            xtype: 'label',
                                            x: 10,
                                            y: 280,
                                            cls: 'textFieldCSS',
                                            height: 10,
                                            text: 'Contact Social Information'
                                        },
                                        {
                                            xtype: 'image',
                                            x: 980,
                                            y: 10,
                                            frame: false,
                                            height: 180,
                                            itemId: 'contactImage',
                                            maxHeight: 180,
                                            maxWidth: 180,
                                            minHeight: 180,
                                            minWidth: 180,
                                            width: 180,
                                            src: 'resources/localData/DefaultPlaceholder.jpg'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'calendarPanel',
                    autoScroll: true,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            frame: true,
                            itemId: 'chooseEventGrid',
                            autoScroll: true,
                            title: 'Choose Event',
                            titleAlign: 'center',
                            store: 'EventDatabaseStore',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    align: 'center',
                                    dataIndex: 'eventDate',
                                    text: 'Event Date',
                                    flex: 1,
                                    format: 'd-m-Y'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    align: 'center',
                                    dataIndex: 'eventName',
                                    text: 'Event Name',
                                    flex: 1
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    autoScroll: true,
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'addEventButton',
                                            text: 'Add Event'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'modEventButton',
                                            text: 'Mod Event'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'deleteEventButton',
                                            text: 'Delete Event'
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'syncEventButton',
                                            text: 'Sync Events'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'optionsEvent',
                                            glyph: 'xf013@FontAwesome'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            flex: 2,
                            frame: true,
                            height: 310,
                            itemId: 'singleEventForm',
                            maxHeight: 310,
                            autoScroll: true,
                            layout: 'absolute',
                            bodyPadding: 10,
                            title: 'Event Information',
                            titleAlign: 'center',
                            items: [
                                {
                                    xtype: 'textfield',
                                    x: 20,
                                    y: 40,
                                    cls: 'textFieldCSS',
                                    itemId: 'eventNameTF',
                                    fieldLabel: 'Event',
                                    labelAlign: 'top',
                                    labelCls: 'x-form-item-label, styleSincbook',
                                    labelSeparator: ' ',
                                    name: 'eventName',
                                    fieldCls: 'x-form-field textFieldCSS',
                                    readOnly: true,
                                    emptyCls: 'x-form-empty-field;',
                                    emptyText: 'Choose an Event',
                                    grow: true
                                },
                                {
                                    xtype: 'textfield',
                                    x: 20,
                                    y: 130,
                                    cls: 'textFieldCSS',
                                    itemId: 'eventDescriptionTF',
                                    fieldLabel: 'Event Description',
                                    labelAlign: 'top',
                                    labelCls: 'x-form-item-label, styleSincbook',
                                    labelSeparator: ' ',
                                    name: 'eventDescription',
                                    fieldCls: 'x-form-field textFieldCSS',
                                    readOnly: true,
                                    emptyCls: 'x-form-empty-field;',
                                    emptyText: 'Choose an Event',
                                    grow: true
                                },
                                {
                                    xtype: 'textfield',
                                    x: 210,
                                    y: 130,
                                    cls: 'textFieldCSS',
                                    itemId: 'eventTypeTF',
                                    fieldLabel: 'Event Type',
                                    labelAlign: 'top',
                                    labelCls: 'x-form-item-label, styleSincbook',
                                    labelSeparator: ' ',
                                    name: 'eventType',
                                    fieldCls: 'x-form-field textFieldCSS',
                                    readOnly: true,
                                    emptyCls: 'x-form-empty-field;',
                                    emptyText: 'Choose an Event',
                                    grow: true
                                },
                                {
                                    xtype: 'textfield',
                                    x: 20,
                                    y: 220,
                                    cls: 'textFieldCSS',
                                    itemId: 'eventLocationTF',
                                    fieldLabel: 'Event Location',
                                    labelAlign: 'top',
                                    labelCls: 'x-form-item-label, styleSincbook',
                                    labelSeparator: ' ',
                                    name: 'eventLocation',
                                    fieldCls: 'x-form-field textFieldCSS',
                                    readOnly: true,
                                    emptyCls: 'x-form-empty-field;',
                                    emptyText: 'Choose an Event',
                                    grow: true
                                },
                                {
                                    xtype: 'textfield',
                                    x: 210,
                                    y: 220,
                                    cls: 'textFieldCSS',
                                    itemId: 'eventUrlTF',
                                    fieldLabel: 'Event URL',
                                    labelAlign: 'top',
                                    labelCls: 'x-form-item-label, styleSincbook',
                                    labelSeparator: ' ',
                                    name: 'eventUrl',
                                    fieldCls: 'x-form-field textFieldCSS',
                                    readOnly: true,
                                    emptyCls: 'x-form-empty-field;',
                                    emptyText: 'Choose an Event',
                                    grow: true
                                },
                                {
                                    xtype: 'label',
                                    x: 10,
                                    y: 10,
                                    cls: 'textFieldCSS',
                                    height: 10,
                                    text: 'Event Basic Information'
                                },
                                {
                                    xtype: 'label',
                                    x: 10,
                                    y: 100,
                                    cls: 'textFieldCSS',
                                    height: 10,
                                    text: 'Event Custom Information'
                                },
                                {
                                    xtype: 'label',
                                    x: 10,
                                    y: 190,
                                    cls: 'textFieldCSS',
                                    height: 10,
                                    text: 'Event Advanced Information'
                                },
                                {
                                    xtype: 'datefield',
                                    x: 210,
                                    y: 40,
                                    cls: 'textFieldCSS',
                                    itemId: 'eventStartDF',
                                    fieldLabel: 'Event Start Date',
                                    labelAlign: 'top',
                                    labelCls: 'x-form-item-label, styleSincbook',
                                    labelSeparator: ' ',
                                    name: 'eventStart',
                                    fieldCls: 'x-form-field textFieldCSS',
                                    readOnly: true,
                                    emptyText: 'Choose an Event',
                                    editable: false,
                                    format: 'd/m/Y - H:i'
                                },
                                {
                                    xtype: 'datefield',
                                    x: 410,
                                    y: 40,
                                    cls: 'textFieldCSS',
                                    itemId: 'eventEndDF',
                                    fieldLabel: 'Event End Date',
                                    labelAlign: 'top',
                                    labelCls: 'x-form-item-label, styleSincbook',
                                    labelSeparator: ' ',
                                    name: 'eventEnd',
                                    fieldCls: 'x-form-field textFieldCSS',
                                    readOnly: true,
                                    emptyText: 'Choose an Event',
                                    editable: false,
                                    format: 'd/m/Y - H:i'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});