/*
 * File: app/view/ModEventWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('syncbook.view.ModEventWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.ModEventWindow_ua',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    height: 430,
    itemId: 'modEventWindow',
    width: 690,
    autoScroll: true,
    layout: 'absolute',
    title: 'Mod Event Window',
    titleAlign: 'center',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    itemId: 'modEventForm',
                    minHeight: 50,
                    minWidth: 50,
                    autoScroll: true,
                    layout: 'absolute',
                    frameHeader: false,
                    titleAlign: 'center',
                    method: 'POST',
                    waitTitle: 'Loading...',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 40,
                            y: 60,
                            frame: false,
                            fieldLabel: 'Event',
                            labelSeparator: ' :',
                            labelWidth: 115,
                            name: 'eventName',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            blankText: 'Required Field',
                            enforceMaxLength: true,
                            maxLength: 32,
                            maxLengthText: 'The maximum length for this field is {32}',
                            minLength: 1,
                            minLengthText: 'The minimum length for this field is {1}'
                        },
                        {
                            xtype: 'datefield',
                            x: 40,
                            y: 100,
                            cls: 'textFieldCSS',
                            itemId: 'eventStartDF',
                            fieldLabel: 'Event Start Date',
                            labelAlign: 'top',
                            labelCls: 'x-form-item-label, styleSincbook',
                            labelSeparator: ' ',
                            name: 'eventStart',
                            fieldCls: 'x-form-field textFieldCSS',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            format: 'd/m/Y',
                            submitFormat: 'Y-m-d'
                        },
                        {
                            xtype: 'datefield',
                            x: 240,
                            y: 100,
                            cls: 'textFieldCSS',
                            itemId: 'eventEndDF',
                            fieldLabel: 'Event End Date',
                            labelAlign: 'top',
                            labelCls: 'x-form-item-label, styleSincbook',
                            labelSeparator: ' ',
                            name: 'eventEnd',
                            fieldCls: 'x-form-field textFieldCSS',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            format: 'd/m/Y',
                            submitFormat: 'Y-m-d'
                        },
                        {
                            xtype: 'timefield',
                            x: 40,
                            y: 150,
                            name: 'eventStartTime',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            emptyText: 'Event Start Time',
                            editable: false,
                            format: 'H:i',
                            increment: 5,
                            snapToIncrement: true,
                            submitFormat: 'H:i'
                        },
                        {
                            xtype: 'timefield',
                            x: 240,
                            y: 150,
                            name: 'eventEndTime',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            emptyText: 'Event End Time',
                            editable: false,
                            format: 'H:i',
                            increment: 5,
                            snapToIncrement: true,
                            submitFormat: 'H:i'
                        },
                        {
                            xtype: 'textfield',
                            x: 40,
                            y: 230,
                            frame: false,
                            fieldLabel: 'Event Description',
                            labelSeparator: ' :',
                            labelWidth: 115,
                            name: 'eventDescription',
                            blankText: 'Required Field',
                            enforceMaxLength: true,
                            maxLength: 32,
                            maxLengthText: 'The maximum length for this field is {32}',
                            minLength: 1,
                            minLengthText: 'The minimum length for this field is {1}'
                        },
                        {
                            xtype: 'combobox',
                            x: 350,
                            y: 220,
                            frame: false,
                            itemId: 'typeComboBox',
                            margin: 10,
                            fieldLabel: 'Type',
                            hideLabel: true,
                            name: 'eventType',
                            blankText: 'Required Field',
                            emptyText: 'Choose Event Type',
                            enforceMaxLength: true,
                            editable: false,
                            displayField: 'label',
                            store: 'EventTypeStore',
                            valueField: 'value'
                        },
                        {
                            xtype: 'textfield',
                            x: 40,
                            y: 310,
                            frame: false,
                            fieldLabel: 'Event Location',
                            labelSeparator: ' :',
                            labelWidth: 115,
                            name: 'eventLocation',
                            blankText: 'Required Field',
                            enforceMaxLength: true,
                            maxLength: 32,
                            maxLengthText: 'The maximum length for this field is {32}',
                            minLength: 1,
                            minLengthText: 'The minimum length for this field is {1}'
                        },
                        {
                            xtype: 'textfield',
                            x: 360,
                            y: 310,
                            frame: false,
                            fieldLabel: 'Event Url',
                            labelSeparator: ' :',
                            labelWidth: 115,
                            name: 'eventUrl',
                            inputType: 'url',
                            blankText: 'Required Field',
                            enforceMaxLength: true,
                            maxLength: 32,
                            maxLengthText: 'The maximum length for this field is {32}',
                            minLength: 1,
                            minLengthText: 'The minimum length for this field is {1}',
                            vtype: 'url'
                        },
                        {
                            xtype: 'label',
                            x: 20,
                            y: 20,
                            frame: false,
                            text: 'EVENT BASIC INFORMATION'
                        },
                        {
                            xtype: 'label',
                            x: 20,
                            y: 190,
                            frame: false,
                            text: 'EVENT CUSTOM INFORMATION'
                        },
                        {
                            xtype: 'label',
                            x: 20,
                            y: 270,
                            frame: false,
                            text: 'EVENT ADVANCED INFORMATION'
                        },
                        {
                            xtype: 'button',
                            x: 600,
                            y: 350,
                            itemId: 'modEventSubmit',
                            text: 'Submit'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});