/*
 * File: app/model/ContactInformationModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('syncbook.model.ContactInformationModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Rest'
    ],

    idProperty: 'ID',

    fields: [
        {
            name: 'ID'
        },
        {
            name: 'contactColor'
        },
        {
            name: 'contactGroup'
        },
        {
            name: 'contactType'
        },
        {
            name: 'contactImage'
        },
        {
            name: 'contactSurname'
        },
        {
            name: 'contactUsername'
        },
        {
            name: 'contactName'
        },
        {
            name: 'contactEMail'
        },
        {
            name: 'contactPhoneNumber'
        },
        {
            name: 'contactMobileNumber'
        },
        {
            name: 'contactFax'
        },
        {
            name: 'contactAddress'
        },
        {
            name: 'contactWeb'
        },
        {
            name: 'contactPartitaIva'
        },
        {
            name: 'contactCodiceFiscale'
        },
        {
            name: 'contactFacebook'
        },
        {
            name: 'contactTwitter'
        },
        {
            name: 'contactInstagram'
        },
        {
            name: 'contactGoogle'
        },
        {
            name: 'contactLinkedin'
        },
        {
            name: 'contactSkype'
        },
        {
            name: 'UUID'
        },
        {
            name: 'errorCode'
        },
        {
            name: 'errorSuccess'
        },
        {
            name: 'errorDescription'
        }
    ],

    proxy: {
        type: 'rest',
        url: 'resources/libraries/syncbookServices/contactService.php/contacts'
    }
});