/*
 * File: app/model/EventInformationModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('syncbook.model.EventInformationModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Rest'
    ],

    idProperty: 'ID',

    fields: [
        {
            name: 'ID'
        },
        {
            name: 'eventDate',
            type: 'date'
        },
        {
            name: 'eventName'
        },
        {
            convert: function(v, rec) {
                return new Date(v);
            },
            name: 'eventStart',
            type: 'date'
        },
        {
            name: 'eventStartTime'
        },
        {
            convert: function(v, rec) {
                return new Date(v);
            },
            name: 'eventEnd',
            type: 'date'
        },
        {
            name: 'eventEndTime'
        },
        {
            name: 'eventDescription'
        },
        {
            name: 'eventLocation'
        },
        {
            name: 'eventUrl'
        },
        {
            name: 'eventType'
        },
        {
            name: 'UUID'
        },
        {
            name: 'errorCode'
        },
        {
            name: 'errorSuccess'
        },
        {
            name: 'errorDescription'
        }
    ],

    proxy: {
        type: 'rest',
        url: 'resources/libraries/syncbookServices/eventService.php/events'
    }
});