/*
 * File: app/controller/ChooseEventController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('syncbook.controller.ChooseEventController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'InitialViewArea',
            selector: 'InitialViewArea_ua'
        }
    ],

    chooseEventGridBeforeRender: function(component, eOpts) {
        /*Before Render Choose Event Grid*/

        // Building a reference for the EventGrid
        var eventGrid = this.getInitialViewArea().getComponent('calendarPanel').getComponent('chooseEventGrid');

        // Adding the ExtraParam for loading the vCalendars to the Store->Proxy, uncomment if needed
        //eventGrid.store.proxy.extraParams.loadingStoreEvents = true;

        // Loading the chooseEventGrid->Store
        eventGrid.store.load({
            callback : function(records, operation, success) {
                if(records.length>0 && records[0].data.errorSuccess === false) {
                    console.error("An error with code : "+records[0].data.errorCode+" has occoured = "+records[0].data.errorDescription);
                }
            }
        });
    },

    eventSelection: function(rowmodel, record, index, eOpts) {
        /*Select a Single Event From Grid*/
        var eventForm = this.getInitialViewArea().getComponent('calendarPanel').getComponent('singleEventForm');
        eventForm.getForm().loadRecord(record);

        if(record.data.eventName!=="") {eventForm.setTitle("Event : "+record.data.eventName);}
    },

    init: function(application) {
        this.control({
            "#chooseEventGrid": {
                beforerender: this.chooseEventGridBeforeRender,
                select: this.eventSelection
            }
        });
    }

});
