/*
 * File: app/controller/ChooseContactController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('syncbook.controller.ChooseContactController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'InitialViewArea',
            selector: 'InitialViewArea_ua'
        }
    ],

    chooseContactGridBeforeRender: function(component, eOpts) {
        // Before Render Choose Contact Grid

        // Building a reference for the ContactGrid
        var contactGrid = this.getInitialViewArea().getComponent('groupTabbedPane').getComponent('groupName').getComponent('chooseContactGrid');

        // Adding the ExtraParam for loading the vCards to the Store->Proxy, uncomment if needed
        //contactGrid.store.proxy.extraParams.loadingStoreContacts = true;

        // Loading the chooseContactGrid->Store
        contactGrid.store.load({
            callback : function(records, operation, success) {
                if(records !== null && records.length>0 && records[0].data.errorSuccess === false) {
                    console.error("An error with code : "+records[0].data.errorCode+" has occoured = "+records[0].data.errorDescription);
                }
            }
        });
    },

    contactSelection: function(rowmodel, record, index, eOpts) {
        /*Select a Single Contact From Grid*/

        var contactForm = this.getInitialViewArea().getComponent('groupTabbedPane').getComponent('groupName').getComponent('singleContactForm');
        contactForm.getForm().loadRecord(record);
        if(record.data.contactUsername!=="") {
            contactForm.setTitle("Contact : "+record.data.contactName+" - "+record.data.contactUsername+" - "+record.data.contactSurname);
        } else {
            contactForm.setTitle("Contact : "+record.data.contactName+" - "+record.data.contactSurname);
        }
    },

    init: function(application) {
        this.control({
            "#chooseContactGrid": {
                beforerender: this.chooseContactGridBeforeRender,
                select: this.contactSelection
            }
        });
    }

});
