var namespace_sabre_1_1_d_a_v_1_1_exception =
[
    [ "BadRequest", "class_sabre_1_1_d_a_v_1_1_exception_1_1_bad_request.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_bad_request" ],
    [ "Conflict", "class_sabre_1_1_d_a_v_1_1_exception_1_1_conflict.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_conflict" ],
    [ "ConflictingLock", "class_sabre_1_1_d_a_v_1_1_exception_1_1_conflicting_lock.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_conflicting_lock" ],
    [ "FileNotFound", "class_sabre_1_1_d_a_v_1_1_exception_1_1_file_not_found.html", null ],
    [ "Forbidden", "class_sabre_1_1_d_a_v_1_1_exception_1_1_forbidden.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_forbidden" ],
    [ "InsufficientStorage", "class_sabre_1_1_d_a_v_1_1_exception_1_1_insufficient_storage.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_insufficient_storage" ],
    [ "InvalidResourceType", "class_sabre_1_1_d_a_v_1_1_exception_1_1_invalid_resource_type.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_invalid_resource_type" ],
    [ "InvalidSyncToken", "class_sabre_1_1_d_a_v_1_1_exception_1_1_invalid_sync_token.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_invalid_sync_token" ],
    [ "LengthRequired", "class_sabre_1_1_d_a_v_1_1_exception_1_1_length_required.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_length_required" ],
    [ "Locked", "class_sabre_1_1_d_a_v_1_1_exception_1_1_locked.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_locked" ],
    [ "LockTokenMatchesRequestUri", "class_sabre_1_1_d_a_v_1_1_exception_1_1_lock_token_matches_request_uri.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_lock_token_matches_request_uri" ],
    [ "MethodNotAllowed", "class_sabre_1_1_d_a_v_1_1_exception_1_1_method_not_allowed.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_method_not_allowed" ],
    [ "NotAuthenticated", "class_sabre_1_1_d_a_v_1_1_exception_1_1_not_authenticated.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_not_authenticated" ],
    [ "NotFound", "class_sabre_1_1_d_a_v_1_1_exception_1_1_not_found.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_not_found" ],
    [ "NotImplemented", "class_sabre_1_1_d_a_v_1_1_exception_1_1_not_implemented.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_not_implemented" ],
    [ "PaymentRequired", "class_sabre_1_1_d_a_v_1_1_exception_1_1_payment_required.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_payment_required" ],
    [ "PreconditionFailed", "class_sabre_1_1_d_a_v_1_1_exception_1_1_precondition_failed.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_precondition_failed" ],
    [ "ReportNotSupported", "class_sabre_1_1_d_a_v_1_1_exception_1_1_report_not_supported.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_report_not_supported" ],
    [ "RequestedRangeNotSatisfiable", "class_sabre_1_1_d_a_v_1_1_exception_1_1_requested_range_not_satisfiable.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_requested_range_not_satisfiable" ],
    [ "ServiceUnavailable", "class_sabre_1_1_d_a_v_1_1_exception_1_1_service_unavailable.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_service_unavailable" ],
    [ "TooManyMatches", "class_sabre_1_1_d_a_v_1_1_exception_1_1_too_many_matches.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_too_many_matches" ],
    [ "UnsupportedMediaType", "class_sabre_1_1_d_a_v_1_1_exception_1_1_unsupported_media_type.html", "class_sabre_1_1_d_a_v_1_1_exception_1_1_unsupported_media_type" ]
];